# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-ghp-workflow',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-ghp-workflow',
                'lib_path': 'test_ghp_workflow'},
  'syms': {'test_ghp_workflow.core': {'test_ghp_workflow.core.foo': ('core.html#foo', 'test_ghp_workflow/core.py')}}}
